### ISSUE TITLE
generate heatmap is slow

### ISSUE THREAD

**Issue by ilovecv** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#1]
Hi,

Thank you very much for sharing the awesome work!
When I used the generate_heapmap.py to generate heatmaps, I found it was a bit slow. May I use CenterLabelHeatMap instead of CenterGaussianHeatMap to generate the heatmap? Will it have a serious effect on the performance? Thank you very much!

**Comment by lightas** [comment]
@ilovecv Hi, I didn't use CenterLabelHeatMap but it seems that CenterLabelHeatMap does the same thing of CenterGaussianHeatMap. So you can have a try.
By the way, I have generated heatmaps for Occluded-Duke, Partial_REID and Partial iLIDS and downloadable links are provided in README.md. You can download them directly.
