### ISSUE TITLE
The img size when uing pose estimator

### ISSUE THREAD

**Issue by MeaninglessAI** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#10]
Hi, in testing stage, the paper use the confidence score of detected landmarks to indicate which part of the target person is occluded and which part is not.

 And I want to know  whether the image size is the same as the training(i.e.384x128) when extracting the landmarks.

**Comment by lightas** [comment]
@MeaninglessAI The image size is the original size (not 384x128) when extracting the landmarks.
