### ISSUE TITLE
关于训练复现，训练market复现精度相差较大

### ISSUE THREAD

**Issue by jayyoung0802** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#12]
您好，我通过您提供的landmark以及heatmap重新进行了训练，在Occluded-DukeMTMC数据集上精度差别不大，在Partial-REID数据集和Partial_iLIDS数据集精度相差较大。请问可以提供一下详细的训练参数吗，或者还有什么训练技巧呀？

1、Occluded-DukeMTMC数据集
       单卡训练，part_num=3, 精度与您论文以及您开源的权值差不多。
                    | Rank-1 | Rank-5 | Rank-10 | mAP
Paper           | 0.514 | 0.686 | 0.749 | 0.373
开源权值     | 0.5208 | 0.6787 | 0.7330 | 0.3861
自己训练     | 0.5231 | 0.6697 | 0.7281 | 0.3737

2、Partial-REID数据集
       单卡训练，part_num=6，在market数据集进行训练，在Partial-REID进行测试，**精度相差较大**。
                    | Rank-1 | Rank-5 | Rank-10 | mAP
Paper           | 0.68 | - | - |  
开源权值     | 0.6900 | 0.8467 | 0.8767 | 0.6149
自己训练     | 0.6533 | 0.8100 | 0.9067 | 0.5985

3、Partial_iLIDS数据集
     单卡训练，part_num=6，在market数据集进行训练，在Partial_iLIDS进行测试，**精度相差较大**。
                   | Rank-1 | Rank-5 | Rank-10 | mAP
Paper          | 0.691 |   |   |  
开源权重    | 0.7143 | 0.8571 | 0.9160 | 0.7469
自己训练    | 0.6639 | 0.8739 | 0.8908 | 0.7073

**Comment by lightas** [comment]
您好，能提供下您训练的具体参数吗。在market上训练时请把lambda（调整两个loss的）改成0.9， part_num改成6，lr改成0.02。 您还可以尝试加random erasing。
另外这两个小数据集由于图片数量较少，所以有可能出现结果不稳定的情况。

**Comment by jayyoung0802** [comment]
您好，我使用的参数是lambda=0.2, lr=0.1，part_num=6, 已按照您提供的参数重新训练，Partial-REID和Partial_iLIDS数据集测试结果如下：
1、Partial-REID数据集，**精度相差较大**。
                 | Rank-1 | Rank-5 | Rank-10 | mAP
Paper        | 0.68 | - | - |  
开源权值  | 0.6900 | 0.8467 | 0.8767 | 0.6149
自己训练  | 0.6533 | 0.8100 | 0.9067 | 0.5985
调参         | 0.6533 | 0.8067 | 0.8700 | 0.5998

2、Partial_iLIDS数据集，**精度与您开源的差不多，略低一点**
                 | Rank-1 | Rank-5 | Rank-10 | mAP
Paper        | 0.691 | - | - |  
开源权重  | 0.7143 | 0.8571 | 0.9160 | 0.7469
自己训练  | 0.6639 | 0.8739 | 0.8908 | 0.7073
调参         |0.7143 | 0.8487 | 0.8992 | 0.7420

在Partial-REID数据集上测试精度还是差一点。
另外，我看到有一个参数是--weight_decay, help中是random erasing probability，这个参数是权值衰减呢还是随机擦除呀，还有这个参数的大小设置是多少呀？

**Comment by lightas** [comment]
--weight_decay   help里面应该写错了，就看字面意思就行。  Partial-REID 这个有点奇怪，结果可能会波动，不会波动这么大，尤其是lr调小了结果应该比lr=0.1高。随机擦除是我后来尝试的，这套代码好像没有。您可以自己加一下。
