### ISSUE TITLE
Why divide by 255? This will make the entire image black , with the loss of attention. 

### ISSUE THREAD

**Issue by anshu0612** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#13]
https://github.com/lightas/ICCV19_Pose_Guided_Occluded_Person_ReID/blob/f3aaf4c9f1bf2b69b7930bf398c7bc75729efa59/AlphaPose/generate_heatmap.py#L58

**Comment by lightas** [comment]
https://github.com/lightas/ICCV19_Pose_Guided_Occluded_Person_ReID/blob/f3aaf4c9f1bf2b69b7930bf398c7bc75729efa59/AlphaPose/generate_heatmap.py#L55
In this line we use *255. This is a redundant operation.
