### ISSUE TITLE
the variance of CenterGaussianHeatMap

### ISSUE THREAD

**Issue by Chuckie-He** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#15]
In the code, the variance of CenterGaussianHeatMap is (imgh * imgw / 1000.). How is this parameter determined? Is there any selection principle? Thank you.

**Comment by lightas** [comment]
@Chuckie-He This is determined by experiments but  I forgot to add the ablation in this paper. In the journal version (https://yu-wu.net/pdf/TNNLS-Occlusion_reid.pdf)  the ablation is shown in fig.6.
