### ISSUE TITLE
Loading of PartialREID Dataset

### ISSUE THREAD

**Issue by ritesh2212** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#2]
Hi,
The process you have mentioned above for the loading dataset for Occuled Duke, we cannot use the same method to load the PartialREID Dataset. Can you provide the step to load the PartialREID Dataset for testing?

**Comment by lightas** [comment]
@ritesh2212  So sorry for the late reply. You can download the loadable datasets by https://drive.google.com/file/d/1ErCEQsNHSHpgZF3-NNj6_OH322vpk8gn/view?usp=sharing.

**Comment by ritesh2212** [comment]
Thanks a lot.
