### ISSUE TITLE
How to train the model on Market-1501

### ISSUE THREAD

**Issue by Mrkkew** [lightas/ICCV19_Pose_Guided_Occluded_Person_ReID#8]
I want to ask that how to train the model on Market-1501？Can you release the heatmaps of Market-1501？
Thank you.

**Comment by lightas** [comment]
Please refer to this issue #6  for heat maps of market-1501.

**Comment by jokerdyy** [comment]
I want to ask that how to train the model on Market-1501？not Occluded_Market-1501
